apiVersion: apps/v1
kind: Deployment
metadata:
  name: las2peer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: las2peer
  template:
    metadata:
      labels:
        io.kompose.service: las2peer
    creationTimestamp: null
    spec:
      tolerations:
      - key: "node-role.kubernetes.io"
        operator: "Equal"
        value: "master"
        effect: "NoSchedule"
      containers:
      - name: las2peer
        image: mslupczynski/las2peer:ma-mslupczynski
        imagePullPolicy: Always 
        ports:
        - containerPort: 9000
        - containerPort: 8080
        volumeMounts:
        - name: node-storage
          mountPath: /app/las2peer/node-storage
        env:
        - name: LAS2PEER_ETH_HOST
          value: las2peer-monitored-geth
      volumes:
      - name: node-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: las2peer
  name: las2peer
spec:
  ports:
  - name: "las2peer"
    port: 9000
  - name: "las2peer-wc"
    port: 8080
  selector:
    io.kompose.service: las2peer
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: las2peer-cluster-ports
  name: las2peer-cluster-ports
spec:
  ports:
  - name: "las2peer-external-webconnector"
    port: 8080
    nodePort: 32319
  - name: "las2peer-external"
    port: 9000
    nodePort: 32320
    protocol: TCP
  - name: "las2peer-ext-pastry-udp"
    port: 9000
    nodePort: 32320
    protocol: UDP
  selector:
    io.kompose.service: las2peer
  type: NodePort