version: "3"
networks:
    las2peernet:
services:
    ethereum-monitor:
        hostname: ethereum-monitor
        container_name: ethereum-monitor
        image: rwthacis/eth-netstats
        command: ["/bin/sh", "-c", "npm start > netstats.log 2>&1"]
        environment:
            - "WS_SECRET=eth-net-stats-secret"
        ports:
            - "3000:3000"
        networks:
            - las2peernet
    ethereum-boot:
        hostname: ethereum-boot
        container_name: ethereum-boot
        depends_on: ["ethereum-monitor"]
        image: rwthacis/monitored-eth-client
        environment:
            - "ETHEREUM_MONITOR=ethereum-monitor:3000"
            - "GETH_VERBOSITY=3"
        ports:
            - "30303"
            - "30303/udp"
            - "8545:8545"
        networks:
            - las2peernet
    las2peer-boot:
        hostname: las2peer-boot
        container_name: las2peer-boot
        depends_on: ["ethereum-boot"]
        image: rwthacis/las2peer
        environment:
            - "LAS2PEER_ETH_HOST=ethereum-boot"
        ports:
            - "9000"
            - "9000/udp"
            - "8001"
            - "8080:8080"
        networks:
            - las2peernet
        stdin_open: true
        tty: true
