version: "3"
networks:
    las2peernet:
services:
    ethereum-monitor:
        hostname: ethereum-monitor
        container_name: ethereum-monitor
        image: tjanson/go-ethereum:netstats
        command: ["/bin/sh", "-c", "npm start > netstats.log 2>&1"]
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            - WS_SECRET=eth-net-stats-secret
        ports:
            - "3000:3000"
        networks:
            - las2peernet
    ethereum-boot:
        hostname: ethereum-boot
        container_name: ethereum-boot
        depends_on: ["ethereum-monitor"]
        image: tjanson/go-ethereum:monitored-client
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            - ETHEREUM_MONITOR=ethereum-monitor:3000
            - GETH_VERBOSITY=1
        ports:
            - "30303"
            - "30303/udp"
            - "8545:8545"
        networks:
            - las2peernet
    las2peer-boot:
        hostname: las2peer-boot
        container_name: las2peer-boot
        depends_on: ["ethereum-boot"]
        image: tjanson/las2peer:autostart-registry
        deploy:
            replicas: 1
            restart_policy:
                condition: none # clean recovery not yet implemented
        environment:
            - LAS2PEER_ETH_HOST=ethereum-boot
        ports:
            - "9000"
            - "9000/udp"
            - "8001"
            - "8080:8080"
        networks:
            - las2peernet
        stdin_open: true
        tty: true
