    ethereum-peer-1:
        container_name: ethereum-peer-1
        hostname: ethereum-peer-1
        depends_on: ["ethereum-monitor", "ethereum-boot"]
        image: rwthacis/monitored-geth-client:difficulty-DIFFICULTY
        cpus: "CPULIMIT"
        environment:
            - "PEER_MINE=1"
            - "ETHEREUM_BOOTSTRAP=ethereum-boot:30303"
            - "ETHEREUM_MONITOR=ethereum-monitor:3000"
            - "GETH_VERBOSITY=3"
        ports:
            - "30303"
            - "30303/udp"
            - "8545"
        networks:
            - las2peernet
    las2peer-peer-1:
        container_name: las2peer-peer-1
        hostname: las2peer-peer-1
        depends_on: ["ethereum-peer-1", "las2peer-boot"]
        image: tjanson/las2peer:develop
        environment:
            - "LAS2PEER_CONFIG_ENDPOINT=172.18.0.10:8001"
            - "LAS2PEER_BOOTSTRAP=172.18.0.10:9000"
            - "LAS2PEER_ETH_HOST=ethereum-peer-1"
        ports:
            - "9000"
            - "9000/udp"
            - "8080"
        networks:
            - las2peernet
        stdin_open: true
        tty: true
